buildscript {
    ext.kotlin_version = '2.2.21'  // ✅ ПОСЛЕДНЯЯ ВЕРСИЯ
    repositories {
        google()
        mavenCentral()
        maven { url 'https://download.linphone.org/releases/android/maven_repository/' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.6'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://download.linphone.org/releases/android/maven_repository/' }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
